#!/usr/bin/env bash

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CONDA_ENVIRONMENT_FILE="${PROJECT_ROOT}/toolchain/environment.yml"
TOOLCHAIN_ROOT="${PROJECT_ROOT}/outputs/toolchain"
ACTIVATION_SCRIPT="${TOOLCHAIN_ROOT}/activate.sh"
CONDA_HOME="${GOALEVOLVE_CONDA_HOME:-${TOOLCHAIN_ROOT}/miniforge3}"
CONDA_PREFIX="${GOALEVOLVE_CONDA_PREFIX:-${TOOLCHAIN_ROOT}/conda-env}"
CONDA_PACKAGES_DIR="${GOALEVOLVE_CONDA_PACKAGES_DIR:-${TOOLCHAIN_ROOT}/conda-pkgs}"
CODEX_PREFIX="${TOOLCHAIN_ROOT}/codex-cli"
INSTALL_CODEX_CLI=0

usage() {
    cat <<'EOF'
Usage: scripts/human/setup.sh [--install-codex-cli]

Bootstraps Miniforge below outputs/toolchain/ when Conda is unavailable and
creates an isolated Python environment there. It does not build OpenROAD or
install system packages. AE-2 and AE-3 use a prepared, version-matched host
OpenROAD/ORFS environment; see README.md.

--install-codex-cli installs @openai/codex inside outputs/toolchain/codex-cli.
It does not create, read, or configure an API key.
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --install-codex-cli) INSTALL_CODEX_CLI=1; shift ;;
        -h|--help) usage; exit 0 ;;
        *) printf 'Unknown option: %s\n' "$1" >&2; usage >&2; exit 2 ;;
    esac
done

mkdir -p "${CONDA_PACKAGES_DIR}" "${TOOLCHAIN_ROOT}/tmp"
if command -v conda >/dev/null 2>&1; then
    CONDA_COMMAND="$(command -v conda)"
elif [[ -x "${CONDA_HOME}/bin/conda" ]]; then
    CONDA_COMMAND="${CONDA_HOME}/bin/conda"
else
    case "$(uname -m)" in
        x86_64|amd64) miniforge_arch="x86_64" ;;
        aarch64|arm64) miniforge_arch="aarch64" ;;
        *) printf 'Unsupported architecture for Miniforge bootstrap: %s\n' "$(uname -m)" >&2; exit 1 ;;
    esac
    if command -v curl >/dev/null 2>&1; then
        downloader=(curl --fail --location --retry 3 --output)
    elif command -v wget >/dev/null 2>&1; then
        downloader=(wget --output-document)
    else
        printf '%s\n' 'Conda is unavailable and neither curl nor wget can bootstrap Miniforge.' >&2
        exit 1
    fi
    installer="${TOOLCHAIN_ROOT}/tmp/Miniforge3-${miniforge_arch}.sh"
    printf '[INFO] Bootstrapping Miniforge under %s\n' "${CONDA_HOME}"
    "${downloader[@]}" "${installer}" "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-${miniforge_arch}.sh"
    bash "${installer}" -b -p "${CONDA_HOME}"
    CONDA_COMMAND="${CONDA_HOME}/bin/conda"
fi

if [[ ! -x "${CONDA_PREFIX}/bin/python" ]]; then
    printf '[INFO] Creating project-local Python environment: %s\n' "${CONDA_PREFIX}"
    # libmamba stores shard metadata in a cache shared by all Conda commands
    # on a host.  On multi-user machines a concurrent solver can briefly lock
    # that SQLite database.  Retry through Conda's classic solver, which does
    # not use the libmamba shard cache, while retaining the same environment
    # file and project-local package cache.
    if ! CONDA_PKGS_DIRS="${CONDA_PACKAGES_DIR}" "${CONDA_COMMAND}" env create --yes --prefix "${CONDA_PREFIX}" --file "${CONDA_ENVIRONMENT_FILE}"; then
        printf '%s\n' '[WARN] Default Conda solver failed; retrying setup with the classic solver.' >&2
        CONDA_SOLVER=classic CONDA_PKGS_DIRS="${CONDA_PACKAGES_DIR}" "${CONDA_COMMAND}" env create --yes --prefix "${CONDA_PREFIX}" --file "${CONDA_ENVIRONMENT_FILE}"
    fi
fi

CONDA_RUN=("${CONDA_COMMAND}" run --no-capture-output --prefix "${CONDA_PREFIX}")
"${CONDA_RUN[@]}" python -c 'import sys; assert sys.version_info >= (3, 11)'
# Keep existing project environments synchronized with pyproject.toml as well
# as provisioning the bindings for a newly-created environment.yml install.
"${CONDA_RUN[@]}" python -m pip install --disable-pip-version-check --upgrade \
    'tree-sitter==0.26.0' 'tree-sitter-cpp==0.23.4'
CODEX_BIN="${CODEX_PREFIX}/node_modules/.bin"
if [[ ${INSTALL_CODEX_CLI} -eq 1 ]]; then
    printf '[INFO] Installing the Codex CLI into project-generated state.\n'
    "${CONDA_RUN[@]}" npm --prefix "${CODEX_PREFIX}" --cache "${TOOLCHAIN_ROOT}/npm-cache" install @openai/codex
fi

"${CONDA_RUN[@]}" python - "${ACTIVATION_SCRIPT}" "${CONDA_PREFIX}" "${CODEX_BIN}" <<'PY'
from pathlib import Path
import shlex
import sys

activation, conda_prefix, codex_bin = map(Path, sys.argv[1:])
quote = lambda value: shlex.quote(str(value.resolve()))
activation.write_text("\n".join((
    "# Generated by scripts/human/setup.sh. Source from Bash.",
    f'export GOALEVOLVE_CONDA_PREFIX={quote(conda_prefix)}',
    f'export PATH={quote(conda_prefix / "bin")}:{quote(codex_bin)}:${{PATH}}',
    "",
)), encoding="utf-8")
PY
chmod 600 "${ACTIVATION_SCRIPT}"

printf '[OK] Project Python: %s\n' "${CONDA_PREFIX}/bin/python"
printf '[OK] Activation script: %s\n' "${ACTIVATION_SCRIPT}"
if [[ -x "${CODEX_BIN}/codex" ]]; then
    printf '[OK] Codex CLI: %s\n' "${CODEX_BIN}/codex"
else
    printf '%s\n' '[INFO] Codex CLI is optional for AE-1/AE-2. Install it with: make setup INSTALL_CODEX_CLI=1'
fi
printf '%s\n' '[INFO] AE-2/AE-3 require a prepared host OpenROAD/ORFS toolchain; see README.md.'
